# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Apterid Programming Language
email: gordon@balafon.net
description: >
  Apterid is a minimalist functional-first language for .NET.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://apterid.org" # the base hostname & protocol for your site
twitter_username: ApteridLang
github_username:  apterid

# Build settings
markdown: kramdown
